
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: licenses.kommander.mesosphere.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.valid
    name: Valid
    type: string
  - JSONPath: .status.startDate
    name: Start date
    type: string
  - JSONPath: .status.endDate
    name: End date
    type: string
  - JSONPath: .status.clusterCapacity
    name: Cluster capacity
    type: string
  - JSONPath: .spec.licenseRef.name
    name: JWT reference
    type: string
  group: kommander.mesosphere.io
  names:
    kind: License
    listKind: LicenseList
    plural: licenses
    singular: license
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: License is the Schema for the licenses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LicenseSpec defines the desired state of License
          properties:
            licenseRef:
              description: LicenseReference holds a single reference to the secret
                holding the license JWT
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
          type: object
        status:
          description: LicenseStatus defines the observed state of License
          properties:
            clusterCapacity:
              description: Maximum number of clusters that the license allows.
              format: int32
              type: integer
            conditions:
              description: Conditions relevant to the license (currently used to track
                term breaches)
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            customerId:
              description: The customer's ID. This is the customer name provided from
                Salesforce.
              type: string
            endDate:
              description: End date of the licensing period.
              format: date-time
              type: string
            licenseId:
              description: The license's ID as provided from Salesforce.
              type: string
            startDate:
              description: Start date of the licensing period.
              format: date-time
              type: string
            valid:
              description: Indicates whether the license is valid, i.e. the secret
                containing the JWT exists and the JWT carries a valid D2iQ signature.
                This does NOT indicate whether the license has expired or terms have
                been breached.
              type: boolean
            version:
              description: The license's version ID as provided when the license was
                created.
              type: string
          required:
          - clusterCapacity
          - customerId
          - licenseId
          - valid
          - version
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
