apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - workspaces.kommander.mesosphere.io
  resources:
    - projects
    - projectroles
    - workspaces
    - workspaceroles
    - virtualgroupprojectrolebindings
    - virtualgroupworkspacerolebindings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - cloudprovideraccounts
  - konvoyclusters
  - kommanderclusters
  - licenses
  - virtualgroups
  - virtualgrouprolebindings
  - virtualgroupclusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - cloudprovideraccounts/status
  - konvoyclusters/status
  - kommanderclusters/status
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - workspaces.kommander.mesosphere.io
  resources:
    - projects/status
    - projectroles/status
    - workspaces/status
    - workspaceroles/status
    - virtualgroupprojectrolebindings/status
    - virtualgroupworkspacerolebindings/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.mesosphere.io
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - types.kubefed.io
  resources:
  - federatednamespaces
  - federatedroles
  - federatedrolebindings
  - federatedclusterrolebindings
  - federatedclusterroles
  - federatedaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - kubeaddons.mesosphere.io
  resources:
    - addonrepositories
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
