apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.containers.manager.replicas }}
  selector:
    matchLabels:
      {{- include "kommander-cluster-lifecycle.commonSelectorLabels" . | nindent 6 }}
      control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
  template:
    metadata:
      labels:
        {{- include "kommander-cluster-lifecycle.commonSelectorLabels" . | nindent 8 }}
        control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
    spec:
      nodeSelector:
        {{- toYaml .Values.commonNodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.commonTolerations | nindent 8 }}
      serviceAccountName: {{ template "kommander-cluster-lifecycle.fullname" . }}-cm
      terminationGracePeriodSeconds: 10
      containers:
      - name: controller-manager
        image: "{{ .Values.controller.containers.manager.image.repository }}:{{ .Values.controller.containers.manager.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.controller.containers.manager.image.pullPolicy }}"
        args:
        - --enable-leader-election
        - --terraform-backend-address=https://{{ template "kommander-cluster-lifecycle.fullname" . }}-tfcb.{{ .Release.Namespace }}.svc
        - --konvoy-image-repository={{ .Values.konvoy.imageRepository }}
        resources:
          {{ with .Values.controller.containers.manager.resources }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      - name: kube-rbac-proxy
        image: "{{ .Values.controller.containers.proxy.image.repository }}:{{ .Values.controller.containers.proxy.image.tag }}"
        imagePullPolicy: "{{ .Values.controller.containers.proxy.image.pullPolicy }}"
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        resources:
          {{ with .Values.controller.containers.proxy.resources }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        ports:
        - containerPort: 8443
          name: https
        - containerPort: 8080
          name: metrics
      securityContext:
        {{ with .Values.controller.securityContext }}
        {{- toYaml . | nindent 8}}
        {{- end }}
