apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if .Values.utilityApiserver.service.annotations }}
    {{ toYaml .Values.utilityApiserver.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-utility-apiserver
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-utility-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  type: {{.Values.utilityApiserver.service.type}}
  ports:
  - name: https
    port: {{ .Values.utilityApiserver.service.port }}
    protocol: TCP
    targetPort: https
    {{- if and .Values.utilityApiserver.service.nodePort (eq "NodePort" .Values.utilityApiserver.service.type) }}
    nodePort: {{ .Values.utilityApiserver.service.nodePort }}
    {{- end }}
  selector:
    {{- include "kommander-cluster-lifecycle.commonSelectorLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-utility-apiserver
