apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ .Release.Namespace }}/{{ template "kommander-cluster-lifecycle.fullname" . }}-webhook-tls
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-defaulting
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-webhook
webhooks:
  - clientConfig:
      service:
        name: kubernetes
        namespace: default
        path: /apis/webhook.kommander.mesosphere.io/v1beta1/defaults
    failurePolicy: Fail
    name: webhook.kommander.mesosphere.io
    rules:
      - apiGroups:
          - kommander.mesosphere.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - konvoyclusters
          - kommanderclusters
          - virtualgroups
    sideEffects: None
  - clientConfig:
      service:
        name: kubernetes
        namespace: default
        path: /apis/webhook.workspaces.kommander.mesosphere.io/v1alpha1/defaults
    failurePolicy: Fail
    name: webhook.workspaces.kommander.mesosphere.io
    rules:
      - apiGroups:
          - workspaces.kommander.mesosphere.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - workspaces
          - projects
    sideEffects: None
