apiVersion: v1
appVersion: v0.50
description: A Helm chart for Karma - an UI for Prometheus Alertmanager
home: https://github.com/prymitive/karma
maintainers:
- email: david@davidkarlsen.com
  name: davidkarlsen
- email: l.mierzwa@gmail.com
  name: prymitive
name: karma
sources:
- https://hub.docker.com/r/lmierzwa/karma/
- https://github.com/prymitive/karma
version: 1.4.0
